organization: codeharborhub

stickers:
  - id: cmh1gvq1000eok004uxmvebx4
    alias: "HTML Mastery"
    description: "Awarded for mastering HTML fundamentals and contributing valuable HTML content."
    tags:
      - html
      - contribution
      - mastery

holobytes:
  - evolvingStickerId: cmh1gvq1000eok004uxmvebx4
    alias: "html_mastery_contributor"
    in: true
