user: ajaydhangar

stickers:
  - id: cmh1gvq1000eok004uxmvebx4
    alias: "HTML Mastery"
    description: "Awarded to contributors for completing or demonstrating mastery in HTML through CodeHarborHub contributions."
    tags:
      - html
      - mastery
      - contribution

holobytes:
  - evolvingStickerId: cmh1gvq1000eok004uxmvebx4
    alias: "html_mastery_contributor"
    in: true
