/**
 * Copyright (c) Ajay Dhangar
 *
 * This file defines the sidebar configuration for the CodeHarborHub Tutorials Docs.
 * Each category represents a tutorial topic like HTML, CSS, JavaScript, React, Git, GitHub, and cyber-security.
 *
 * Licensed under the MIT License.
 */

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorial: [
    // "index",

    // Machine LearningTutorial Structure

    // {
    //   type: "link",
    //   label: "Machine Learning",
    //   href: "/ai-ml/machine-learning/",
    // },
    // "ai-agents/index"

    { type: "autogenerated", dirName: "." },
  ],
  ml: [
    "machine-learning/index",
    {
      type: "category",
      label: "Introduction",
      link: {
        type: "generated-index",
        title: "Introduction to Machine Learning",
        description:
          "Get started with Machine Learning. Understand what ML is, the role of an ML engineer, career paths, and the complete ML lifecycle.",
        keywords: [
          "machine learning introduction",
          "ml engineer",
          "ml lifecycle",
          "ai vs ml",
        ],
      },
      items: [
        "machine-learning/introduction/what-is-ml",
        "machine-learning/introduction/role-of-ml-engineer",
        "machine-learning/introduction/ml-engineer-vs-ai-engineer",
        "machine-learning/introduction/skills-and-responsibilities",
        "machine-learning/introduction/ml-lifecycle",
      ],
    },

    {
      type: "category",
      label: "Mathematics for ML",
      link: {
        type: "generated-index",
        title: "Mathematics for Machine Learning",
        description:
          "Build strong mathematical foundations required for Machine Learning. This section covers Linear Algebra, Calculus, and Discrete Mathematics with ML-focused explanations and examples.",
        keywords: [
          "mathematics for machine learning",
          "math for ML",
          "linear algebra for ML",
          "calculus for ML",
          "discrete mathematics for ML",
        ],
      },
      items: [
        // =========================
        // Linear Algebra
        // =========================
        {
          type: "category",
          label: "Linear Algebra",
          link: {
            type: "generated-index",
            title: "Linear Algebra for Machine Learning",
            description:
              "Learn core Linear Algebra concepts used in Machine Learning, including vectors, matrices, eigenvalues, and matrix decompositions.",
            keywords: [
              "linear algebra for machine learning",
              "vectors",
              "matrices",
              "eigenvalues",
              "singular value decomposition",
            ],
          },
          items: [
            "machine-learning/mathematics-for-ml/linear-algebra/scalars",
            "machine-learning/mathematics-for-ml/linear-algebra/vectors",
            "machine-learning/mathematics-for-ml/linear-algebra/matrices",
            "machine-learning/mathematics-for-ml/linear-algebra/tensors",
            "machine-learning/mathematics-for-ml/linear-algebra/matrix-operations",
            "machine-learning/mathematics-for-ml/linear-algebra/determinants",
            "machine-learning/mathematics-for-ml/linear-algebra/inverse-of-matrix",
            "machine-learning/mathematics-for-ml/linear-algebra/eigenvalues-and-eigenvectors",
            "machine-learning/mathematics-for-ml/linear-algebra/svd",
            "machine-learning/mathematics-for-ml/linear-algebra/diagonalization",
          ],
        },

        // =========================
        // Calculus
        // =========================
        {
          type: "category",
          label: "Calculus",
          link: {
            type: "generated-index",
            title: "Calculus for Machine Learning",
            description:
              "Understand how Calculus powers optimization in Machine Learning, including gradients, Jacobians, Hessians, and backpropagation.",
            keywords: [
              "calculus for machine learning",
              "derivatives",
              "gradients",
              "jacobian",
              "hessian",
            ],
          },
          items: [
            "machine-learning/mathematics-for-ml/calculus/derivatives",
            "machine-learning/mathematics-for-ml/calculus/partial-derivatives",
            "machine-learning/mathematics-for-ml/calculus/chain-rule",
            "machine-learning/mathematics-for-ml/calculus/gradients",
            "machine-learning/mathematics-for-ml/calculus/jacobian",
            "machine-learning/mathematics-for-ml/calculus/hessian",
          ],
        },

        // =========================
        // Discrete Mathematics
        // =========================
        {
          type: "category",
          label: "Discrete Mathematics",
          link: {
            type: "generated-index",
            title: "Discrete Mathematics for Machine Learning",
            description:
              "Explore discrete mathematical concepts essential for ML algorithms, graph-based models, and computational reasoning.",
            keywords: [
              "discrete mathematics for machine learning",
              "sets and relations",
              "logic",
              "combinatorics",
              "graph theory",
            ],
          },
          items: [
            "machine-learning/mathematics-for-ml/discrete-mathematics/sets-and-relations",
            "machine-learning/mathematics-for-ml/discrete-mathematics/logic",
            "machine-learning/mathematics-for-ml/discrete-mathematics/combinatorics",
            "machine-learning/mathematics-for-ml/discrete-mathematics/graphs",
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Statistics",
      link: {
        type: "generated-index",
        title: "Statistics for Machine Learning",
        description:
          "Learn descriptive and inferential statistics, data visualization, and statistical reasoning used in ML models.",
        keywords: [
          "statistics",
          "descriptive statistics",
          "inferential statistics",
        ],
      },
      items: [
        "machine-learning/statistics/basic-concepts",
        "machine-learning/statistics/descriptive-statistics",
        "machine-learning/statistics/data-visualization",
        "machine-learning/statistics/inferential-statistics",
      ],
    },

    {
      type: "category",
      label: "Probability",
      link: {
        type: "generated-index",
        title: "Probability for Machine Learning",
        description:
          "Understand probability theory, Bayes theorem, random variables, and probability distributions used in ML.",
        keywords: ["probability", "bayes theorem", "random variables"],
      },
      items: [
        "machine-learning/probability/basics-of-probability",
        "machine-learning/probability/conditional-probability",
        "machine-learning/probability/bayes-theorem",
        "machine-learning/probability/random-variables",
        "machine-learning/probability/pdf-pmf",
        {
          type: "category",
          label: "Distributions",
          link: {
            type: "generated-index",
            title: "Probability Distributions for Machine Learning",
            description:
              "Learn the most important probability distributions used in Machine Learning and Data Science. This section explains Normal, Binomial, Poisson, and Uniform distributions with intuition, formulas, and real-world ML examples.",
            keywords: [
              "probability distributions",
              "probability for machine learning",
              "normal distribution",
              "binomial distribution",
              "poisson distribution",
              "uniform distribution",
            ],
          },
          items: [
            "machine-learning/probability/probability-distributions/normal",
            "machine-learning/probability/probability-distributions/binomial",
            "machine-learning/probability/probability-distributions/poisson",
            "machine-learning/probability/probability-distributions/uniform",
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Programming Fundamentals",
      link: {
        type: "generated-index",
        title: "Programming Fundamentals for ML",
        description:
          "Learn Python programming fundamentals and essential libraries used in Machine Learning workflows.",
        keywords: ["python for ml", "numpy", "pandas", "matplotlib"],
      },
      items: [
        "machine-learning/programming-fundamentals/python",
        {
          type: "category",
          label: "Basic Syntax",
          link: {
            type: "generated-index",
            title: "Python Basic Syntax for Machine Learning",
            description:
              "Learn the core Python syntax required for Machine Learning. This section covers variables, data types, control flow, data structures, functions, and exception handling with ML-focused examples.",
            keywords: [
              "python basic syntax",
              "python for machine learning",
              "variables and data types",
              "python data structures",
              "loops and conditionals",
              "python functions",
              "exception handling in python",
            ],
          },
          items: [
            "machine-learning/programming-fundamentals/basic-syntax/variables-and-data-types",
            "machine-learning/programming-fundamentals/basic-syntax/data-structures",
            "machine-learning/programming-fundamentals/basic-syntax/loops",
            "machine-learning/programming-fundamentals/basic-syntax/conditionals",
            "machine-learning/programming-fundamentals/basic-syntax/exceptions",
            "machine-learning/programming-fundamentals/basic-syntax/functions",
          ],
        },
        "machine-learning/programming-fundamentals/object-oriented-programming",
        {
          type: "category",
          label: "Essential Libraries",
          link: {
            type: "generated-index",
            title: "Essential Python Libraries for Machine Learning",
            description:
              "Master the core Python libraries used in Machine Learning and Data Science. Learn NumPy for numerical computing, Pandas for data manipulation, Matplotlib for visualization, and Seaborn for statistical data exploration.",
            keywords: [
              "python libraries for machine learning",
              "numpy",
              "pandas",
              "matplotlib",
              "seaborn",
              "data science libraries",
              "machine learning tools",
              "python data analysis",
              "data visualization",
            ],
          },
          items: [
            "machine-learning/programming-fundamentals/essential-libraries/numpy",
            "machine-learning/programming-fundamentals/essential-libraries/pandas",
            "machine-learning/programming-fundamentals/essential-libraries/matplotlib",
            "machine-learning/programming-fundamentals/essential-libraries/seaborn",
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Data Engineering Basics",
      link: {
        type: "generated-index",
        title: "Data Engineering Basics for Machine Learning",
        description:
          "Learn how real-world data is collected, stored, cleaned, and prepared for Machine Learning. This section covers data sources, formats, and preprocessing techniques essential for building reliable ML pipelines.",
        keywords: [
          "data engineering for machine learning",
          "data collection",
          "data preprocessing",
          "data formats",
          "feature engineering",
          "machine learning pipelines",
        ],
      },
      items: [
        {
          type: "category",
          label: "Data Collection",
          link: {
            type: "generated-index",
            title: "Data Collection for Machine Learning",
            description:
              "Understand where data comes from and how it is collected for Machine Learning systems, including databases, APIs, the internet, mobile apps, and IoT devices.",
            keywords: [
              "data collection",
              "data sources",
              "sql",
              "nosql",
              "apis",
              "iot data",
              "machine learning data",
            ],
          },
          items: [
            "machine-learning/data-engineering-basics/data-collection/data-sources",
            "machine-learning/data-engineering-basics/data-collection/databases-sql-nosql",
            "machine-learning/data-engineering-basics/data-collection/internet",
            "machine-learning/data-engineering-basics/data-collection/apis",
            "machine-learning/data-engineering-basics/data-collection/mobile-apps",
            "machine-learning/data-engineering-basics/data-collection/iot",
          ],
        },

        {
          type: "category",
          label: "Data Formats",
          link: {
            type: "generated-index",
            title: "Common Data Formats in Machine Learning",
            description:
              "Learn about the most common data formats used in Machine Learning workflows, including tabular, semi-structured, and columnar formats, and understand when to use each.",
            keywords: [
              "data formats",
              "csv",
              "json",
              "parquet",
              "xml",
              "excel data",
              "machine learning datasets",
            ],
          },
          items: [
            "machine-learning/data-engineering-basics/data-formats/csv",
            "machine-learning/data-engineering-basics/data-formats/excel",
            "machine-learning/data-engineering-basics/data-formats/json",
            "machine-learning/data-engineering-basics/data-formats/parquet",
            "machine-learning/data-engineering-basics/data-formats/xml",
          ],
        },

        {
          type: "category",
          label: "Data Cleaning & Preprocessing",
          link: {
            type: "generated-index",
            title: "Data Cleaning and Preprocessing for ML",
            description:
              "Prepare raw data for Machine Learning by handling missing values, engineering features, scaling data, reducing dimensionality, and selecting the most relevant features.",
            keywords: [
              "data cleaning",
              "data preprocessing",
              "feature engineering",
              "feature scaling",
              "normalization",
              "dimensionality reduction",
              "feature selection",
            ],
          },
          items: [
            "machine-learning/data-engineering-basics/data-cleaning-and-preprocessing/handling-missing-data",
            "machine-learning/data-engineering-basics/data-cleaning-and-preprocessing/feature-engineering",
            "machine-learning/data-engineering-basics/data-cleaning-and-preprocessing/feature-scaling",
            "machine-learning/data-engineering-basics/data-cleaning-and-preprocessing/normalization",
            "machine-learning/data-engineering-basics/data-cleaning-and-preprocessing/dimensionality-reduction",
            "machine-learning/data-engineering-basics/data-cleaning-and-preprocessing/feature-selection",
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Machine Learning Core",
      link: {
        type: "generated-index",
        title: "Machine Learning Core Concepts",
        description:
          "Dive into the core concepts of Machine Learning. Learn how ML works, explore different learning paradigms, implement models using Scikit-learn, and understand evaluation techniques used in real-world ML systems.",
        keywords: [
          "machine learning core",
          "introduction to machine learning",
          "types of machine learning",
          "scikit-learn",
          "ml algorithms",
          "model evaluation",
        ],
      },
      items: [
        "machine-learning/machine-learning-core/introduction-to-ml",

        {
          type: "category",
          label: "Types of Machine Learning",
          link: {
            type: "generated-index",
            title: "Types of Machine Learning",
            description:
              "Understand the different learning paradigms in Machine Learning, including supervised, unsupervised, semi-supervised, self-supervised, and reinforcement learning.",
            keywords: [
              "types of machine learning",
              "supervised learning",
              "unsupervised learning",
              "reinforcement learning",
              "semi-supervised learning",
              "self-supervised learning",
            ],
          },
          items: [
            "machine-learning/machine-learning-core/types-of-machine-learning/supervised-learning",
            "machine-learning/machine-learning-core/types-of-machine-learning/unsupervised-learning",
            "machine-learning/machine-learning-core/types-of-machine-learning/semi-supervised-learning",
            "machine-learning/machine-learning-core/types-of-machine-learning/self-supervised-learning",
            "machine-learning/machine-learning-core/types-of-machine-learning/reinforcement-learning",
          ],
        },

        {
          type: "category",
          label: "Scikit-learn",
          link: {
            type: "generated-index",
            title: "Scikit-learn for Machine Learning",
            description:
              "Learn how to build end-to-end Machine Learning workflows using Scikit-learn, from data loading and preprocessing to model selection, tuning, and making predictions.",
            keywords: [
              "scikit-learn",
              "machine learning pipelines",
              "data preparation",
              "model selection",
              "hyperparameter tuning",
            ],
          },
          items: [
            "machine-learning/machine-learning-core/scikit-learn/data-loading",
            "machine-learning/machine-learning-core/scikit-learn/text-data",
            "machine-learning/machine-learning-core/scikit-learn/data-preparation",
            "machine-learning/machine-learning-core/scikit-learn/model-selection",
            "machine-learning/machine-learning-core/scikit-learn/hyperparameter-tuning",
            "machine-learning/machine-learning-core/scikit-learn/predictions",
          ],
        },

        {
          type: "category",
          label: "Supervised Learning",
          link: {
            type: "generated-index",
            title: "Supervised Learning Algorithms",
            description:
              "Learn supervised learning techniques where models are trained using labeled data. Explore classification and regression algorithms widely used in industry.",
            keywords: [
              "supervised learning",
              "classification algorithms",
              "regression algorithms",
              "labeled data",
            ],
          },
          items: [
            {
              type: "category",
              label: "Classification",
              link: {
                type: "generated-index",
                title: "Classification Algorithms",
                description:
                  "Explore classification algorithms used to predict discrete class labels, including distance-based, probabilistic, margin-based, and tree-based methods.",
                keywords: [
                  "classification",
                  "knn",
                  "logistic regression",
                  "svm",
                  "decision trees",
                  "random forest",
                  "gradient boosting",
                ],
              },
              items: [
                "machine-learning/machine-learning-core/supervised-learning/classification/knn",
                "machine-learning/machine-learning-core/supervised-learning/classification/logistic-regression",
                "machine-learning/machine-learning-core/supervised-learning/classification/svm",
                "machine-learning/machine-learning-core/supervised-learning/classification/decision-trees",
                "machine-learning/machine-learning-core/supervised-learning/classification/random-forest",
                "machine-learning/machine-learning-core/supervised-learning/classification/gradient-boosting",
              ],
            },

            {
              type: "category",
              label: "Regression",
              link: {
                type: "generated-index",
                title: "Regression Algorithms",
                description:
                  "Learn regression techniques used to predict continuous values. Understand linear and regularized regression models and their practical applications.",
                keywords: [
                  "regression",
                  "linear regression",
                  "lasso",
                  "ridge",
                  "elastic net",
                  "polynomial regression",
                ],
              },
              items: [
                "machine-learning/machine-learning-core/supervised-learning/regression/linear-regression",
                "machine-learning/machine-learning-core/supervised-learning/regression/polynomial-regression",
                "machine-learning/machine-learning-core/supervised-learning/regression/lasso",
                "machine-learning/machine-learning-core/supervised-learning/regression/ridge",
                "machine-learning/machine-learning-core/supervised-learning/regression/elastic-net",
              ],
            },
          ],
        },

        {
          type: "category",
          label: "Unsupervised Learning",
          link: {
            type: "generated-index",
            title: "Unsupervised Learning Algorithms",
            description:
              "Discover unsupervised learning methods used to uncover hidden patterns in unlabeled data, including clustering and dimensionality reduction techniques.",
            keywords: [
              "unsupervised learning",
              "clustering",
              "dimensionality reduction",
              "kmeans",
              "pca",
            ],
          },
          items: [
            {
              type: "category",
              label: "Clustering",
              link: {
                type: "generated-index",
                title: "Clustering Algorithms",
                description:
                  "Learn clustering techniques that group similar data points together, helping in customer segmentation, anomaly detection, and exploratory analysis.",
                keywords: [
                  "clustering",
                  "kmeans",
                  "hierarchical clustering",
                  "dbscan",
                  "gaussian mixture models",
                ],
              },
              items: [
                "machine-learning/machine-learning-core/unsupervised-learning/clustering/kmeans",
                "machine-learning/machine-learning-core/unsupervised-learning/clustering/hierarchical",
                "machine-learning/machine-learning-core/unsupervised-learning/clustering/dbscan",
                "machine-learning/machine-learning-core/unsupervised-learning/clustering/gaussian-mixtures",
              ],
            },

            {
              type: "category",
              label: "Dimensionality Reduction",
              link: {
                type: "generated-index",
                title: "Dimensionality Reduction Techniques",
                description:
                  "Reduce feature space complexity while preserving important information using techniques like PCA and Autoencoders.",
                keywords: [
                  "dimensionality reduction",
                  "pca",
                  "autoencoders",
                  "feature reduction",
                ],
              },
              items: [
                "machine-learning/machine-learning-core/unsupervised-learning/dimensionality-reduction/pca",
                "machine-learning/machine-learning-core/unsupervised-learning/dimensionality-reduction/autoencoders",
              ],
            },
          ],
        },

        {
          type: "category",
          label: "Reinforcement Learning",
          link: {
            type: "generated-index",
            title: "Reinforcement Learning Fundamentals",
            description:
              "Learn how agents interact with environments to make sequential decisions using reward-based learning strategies.",
            keywords: [
              "reinforcement learning",
              "q-learning",
              "policy gradients",
              "actor critic",
              "deep q networks",
            ],
          },
          items: [
            "machine-learning/machine-learning-core/reinforcement-learning/q-learning",
            "machine-learning/machine-learning-core/reinforcement-learning/policy-gradients",
            "machine-learning/machine-learning-core/reinforcement-learning/actor-critic",
            "machine-learning/machine-learning-core/reinforcement-learning/deep-q-networks",
          ],
        },

        {
          type: "category",
          label: "Model Evaluation",
          link: {
            type: "generated-index",
            title: "Model Evaluation and Validation",
            description:
              "Learn how to evaluate Machine Learning models using appropriate metrics and validation strategies to ensure reliability and generalization.",
            keywords: [
              "model evaluation",
              "ml metrics",
              "cross validation",
              "train test split",
              "model performance",
            ],
          },
          items: [
            "machine-learning/machine-learning-core/model-evaluation/why-evaluation-matters",

            {
              type: "category",
              label: "Metrics",
              link: {
                type: "generated-index",
                title: "Machine Learning Evaluation Metrics",
                description:
                  "Understand performance metrics used to evaluate classification and regression models.",
                keywords: [
                  "accuracy",
                  "precision",
                  "recall",
                  "f1 score",
                  "roc auc",
                  "confusion matrix",
                ],
              },
              items: [
                "machine-learning/machine-learning-core/model-evaluation/metrics/accuracy",
                "machine-learning/machine-learning-core/model-evaluation/metrics/precision",
                "machine-learning/machine-learning-core/model-evaluation/metrics/recall",
                "machine-learning/machine-learning-core/model-evaluation/metrics/f1-score",
                "machine-learning/machine-learning-core/model-evaluation/metrics/roc-auc",
                "machine-learning/machine-learning-core/model-evaluation/metrics/log-loss",
                "machine-learning/machine-learning-core/model-evaluation/metrics/confusion-matrix",
              ],
            },

            {
              type: "category",
              label: "Validation Techniques",
              link: {
                type: "generated-index",
                title: "Model Validation Techniques",
                description:
                  "Learn validation strategies to test model generalization and avoid overfitting.",
                keywords: [
                  "train test split",
                  "k-fold cross validation",
                  "loocv",
                  "model validation",
                ],
              },
              items: [
                "machine-learning/machine-learning-core/model-evaluation/validation-techniques/train-test-split",
                "machine-learning/machine-learning-core/model-evaluation/validation-techniques/k-fold-cross-validation",
                "machine-learning/machine-learning-core/model-evaluation/validation-techniques/loocv",
              ],
            },
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Deep Learning",
      link: {
        type: "generated-index",
        title: "Deep Learning",
        description:
          "Explore Deep Learning from fundamentals to advanced architectures. Learn how neural networks work, use popular frameworks, and build real-world applications using CNNs, RNNs, Transformers, Autoencoders, and GANs.",
        keywords: [
          "deep learning",
          "neural networks",
          "cnn",
          "rnn",
          "transformers",
          "autoencoders",
          "gans",
          "deep learning frameworks",
        ],
      },
      items: [
        {
          type: "category",
          label: "Neural Network Basics",
          link: {
            type: "generated-index",
            title: "Neural Network Fundamentals",
            description:
              "Understand the core building blocks of neural networks, including perceptrons, multilayer networks, forward and backward propagation, activation functions, and loss functions.",
            keywords: [
              "neural network basics",
              "perceptron",
              "mlp",
              "backpropagation",
              "activation functions",
              "loss functions",
            ],
          },
          items: [
            "machine-learning/deep-learning/neural-network-basics/perceptron",
            "machine-learning/deep-learning/neural-network-basics/multi-layer-perceptron",
            "machine-learning/deep-learning/neural-network-basics/forward-propagation",
            "machine-learning/deep-learning/neural-network-basics/backpropagation",
            "machine-learning/deep-learning/neural-network-basics/activation-functions",
            "machine-learning/deep-learning/neural-network-basics/loss-functions",
          ],
        },

        {
          type: "category",
          label: "Deep Learning Libraries",
          link: {
            type: "generated-index",
            title: "Deep Learning Libraries",
            description:
              "Learn popular deep learning frameworks used in industry and research, including TensorFlow, Keras, and PyTorch.",
            keywords: [
              "deep learning libraries",
              "tensorflow",
              "keras",
              "pytorch",
              "neural network frameworks",
            ],
          },
          items: [
            "machine-learning/deep-learning/deep-learning-libraries/tensorflow",
            "machine-learning/deep-learning/deep-learning-libraries/keras",
            "machine-learning/deep-learning/deep-learning-libraries/pytorch",
          ],
        },

        {
          type: "category",
          label: "Convolutional Neural Networks (CNNs)",
          link: {
            type: "generated-index",
            title: "Convolutional Neural Networks",
            description:
              "Learn how CNNs work and why they are powerful for image and video processing tasks. Understand convolution, pooling, padding, and stride operations.",
            keywords: [
              "cnn",
              "convolutional neural networks",
              "image processing",
              "feature maps",
              "pooling",
            ],
          },
          items: [
            "machine-learning/deep-learning/cnn/convolution",
            "machine-learning/deep-learning/cnn/pooling",
            "machine-learning/deep-learning/cnn/padding",
            "machine-learning/deep-learning/cnn/strides",
          ],
        },

        {
          type: "category",
          label: "CNN Applications",
          link: {
            type: "generated-index",
            title: "Applications of CNNs",
            description:
              "Explore real-world applications of Convolutional Neural Networks including image classification, segmentation, video recognition, and recommendation systems.",
            keywords: [
              "cnn applications",
              "image classification",
              "image segmentation",
              "video recognition",
              "recommendation systems",
            ],
          },
          items: [
            "machine-learning/deep-learning/cnn-applications/image-classification",
            "machine-learning/deep-learning/cnn-applications/image-segmentation",
            "machine-learning/deep-learning/cnn-applications/video-recognition",
            "machine-learning/deep-learning/cnn-applications/recommendation-systems",
          ],
        },

        {
          type: "category",
          label: "Recurrent Neural Networks (RNNs)",
          link: {
            type: "generated-index",
            title: "Recurrent Neural Networks",
            description:
              "Understand sequence-based neural networks used for time-series, text, and sequential data. Learn RNNs, GRUs, and LSTMs.",
            keywords: [
              "rnn",
              "recurrent neural networks",
              "gru",
              "lstm",
              "sequence models",
            ],
          },
          items: [
            "machine-learning/deep-learning/rnn/rnn-basics",
            "machine-learning/deep-learning/rnn/gru",
            "machine-learning/deep-learning/rnn/lstm",
          ],
        },

        {
          type: "category",
          label: "Attention Mechanisms",
          link: {
            type: "generated-index",
            title: "Attention Mechanisms & Transformers",
            description:
              "Learn how attention mechanisms revolutionized deep learning. Understand self-attention, transformers, and multi-head attention.",
            keywords: [
              "attention mechanism",
              "self attention",
              "transformers",
              "multi-head attention",
              "nlp models",
            ],
          },
          items: [
            "machine-learning/deep-learning/attention-mechanisms/self-attention",
            "machine-learning/deep-learning/attention-mechanisms/transformers",
            "machine-learning/deep-learning/attention-mechanisms/multi-head-attention",
          ],
        },

        "machine-learning/deep-learning/autoencoders",
        "machine-learning/deep-learning/gans",
      ],
    },

    {
      type: "category",
      label: "Advanced ML Topics",
      link: {
        type: "generated-index",
        title: "Advanced Machine Learning Topics",
        description:
          "Dive into advanced areas of Machine Learning including Natural Language Processing, Explainable AI, MLOps, AI Agents, and the AI Engineer roadmap. Learn how ML systems are built, deployed, monitored, and scaled in production.",
        keywords: [
          "advanced machine learning",
          "nlp",
          "explainable ai",
          "mlops",
          "ai agents",
          "ai engineer roadmap",
        ],
      },
      items: [
        {
          type: "category",
          label: "Natural Language Processing (NLP)",
          link: {
            type: "generated-index",
            title: "Natural Language Processing",
            description:
              "Learn how machines understand human language. Explore text preprocessing, embeddings, attention-based models, and modern NLP techniques used in real-world applications.",
            keywords: [
              "nlp",
              "tokenization",
              "stemming",
              "lemmatization",
              "embeddings",
              "attention models",
            ],
          },
          items: [
            "machine-learning/advanced-ml-topics/natural-language-processing/tokenization",
            "machine-learning/advanced-ml-topics/natural-language-processing/stemming",
            "machine-learning/advanced-ml-topics/natural-language-processing/lemmatization",
            "machine-learning/advanced-ml-topics/natural-language-processing/embeddings",
            "machine-learning/advanced-ml-topics/natural-language-processing/attention-models",
          ],
        },

        {
          type: "category",
          label: "Explainable AI (XAI)",
          link: {
            type: "generated-index",
            title: "Explainable AI",
            description:
              "Understand how to interpret and explain machine learning models. Learn why explainability matters and explore popular techniques like LIME and SHAP.",
            keywords: [
              "explainable ai",
              "xai",
              "lime",
              "shap",
              "model interpretability",
            ],
          },
          items: [
            "machine-learning/advanced-ml-topics/explainable-ai/xai-basics",
            "machine-learning/advanced-ml-topics/explainable-ai/lime-shap",
          ],
        },

        {
          type: "category",
          label: "MLOps",
          link: {
            type: "generated-index",
            title: "MLOps & Production ML",
            description:
              "Learn how to deploy, monitor, and maintain machine learning models in production. Understand CI/CD pipelines, data versioning, reproducibility, and model monitoring.",
            keywords: [
              "mlops",
              "model deployment",
              "monitoring",
              "ci cd",
              "data versioning",
              "reproducibility",
            ],
          },
          items: [
            "machine-learning/advanced-ml-topics/mlops/model-deployment",
            "machine-learning/advanced-ml-topics/mlops/monitoring",
            "machine-learning/advanced-ml-topics/mlops/ci-cd",
            "machine-learning/advanced-ml-topics/mlops/data-versioning",
            "machine-learning/advanced-ml-topics/mlops/reproducibility",
          ],
        },

        {
          type: "category",
          label: "AI Agents",
          link: {
            type: "generated-index",
            title: "AI Agents",
            description:
              "Explore autonomous AI agents capable of planning, reasoning, and acting. Learn how modern agent systems work and how they integrate with tools, APIs, and LLMs.",
            keywords: [
              "ai agents",
              "autonomous agents",
              "llm agents",
              "tool calling",
              "agent workflows",
            ],
          },
          items: [
            "machine-learning/advanced-ml-topics/ai-agents/what-are-ai-agents",
            "machine-learning/advanced-ml-topics/ai-agents/types-of-ai-agents",
            "machine-learning/advanced-ml-topics/ai-agents/agent-architecture",
            "machine-learning/advanced-ml-topics/ai-agents/llm-powered-agents",
            "machine-learning/advanced-ml-topics/ai-agents/tool-using-agents",
            "machine-learning/advanced-ml-topics/ai-agents/planning-and-reasoning",
            "machine-learning/advanced-ml-topics/ai-agents/memory-in-agents",
            "machine-learning/advanced-ml-topics/ai-agents/autonomous-task-agents",
            "machine-learning/advanced-ml-topics/ai-agents/multi-agent-systems",
            "machine-learning/advanced-ml-topics/ai-agents/ai-agent-use-cases",
          ],
        },

        "machine-learning/advanced-ml-topics/ai-engineer-roadmap",
      ],
    },

    {
      type: "category",
      label: "Projects & Case Studies",
      link: {
        type: "generated-index",
        title: "Machine Learning Projects & Case Studies",
        description:
          "Apply your ML knowledge through hands-on projects and real-world industry case studies.",
        keywords: ["ml projects", "case studies", "hands-on machine learning"],
      },
      items: [
        "machine-learning/projects-and-case-studies/beginner-projects",
        "machine-learning/projects-and-case-studies/intermediate-projects",
        "machine-learning/projects-and-case-studies/advanced-projects",
        "machine-learning/projects-and-case-studies/industry-case-studies",
      ],
    },
  ],
};

export default sidebars;
